 This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Tests for iOS"
  lane :unit_test do
    scan(scheme: "waosSwift") # Change to your schema
    xcov(
      scheme: "waosSwift", # Change to your schema
      output_directory: "xcov_output",
      ignore_file_path: ".xcovignore"
    )
  end
end